### PR TITLE
Prevent panic in membership updater

### LINKED ISSUE #1016: inbound federation stopped after some time
Seeing some typing, but no PDUs, looks like it's a bit upset about the room state or something from the logs?

```
time="2020-05-10T17:53:45.283776813Z" level=info msg=Responding func="OnIncomingSyncRequest\n\t" file=" [/build/syncapi/sync/requestpool.go:126]" next=s754_449 req.id=iBHui12cMQsd req.method=GET req.path=/_matrix/client/r0/sync since=s754_448 timed_out=false timeout=30s userID="@half-shot:den.half-shot.uk" user_id="@half-shot:den.half-shot.uk"
time="2020-05-10T17:53:45.283842258Z" level=info msg="Responding (693 bytes)" func="respond\n\t" file=" [/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:170]" code=200 req.id=iBHui12cMQsd req.method=GET req.path=/_matrix/client/r0/sync
time="2020-05-10T17:53:45.289100515Z" level=info msg=Responding func="OnIncomingSyncRequest\n\t" file=" [/build/syncapi/sync/requestpool.go:126]" next=s754_449 req.id=v5cHco2LHEl6 req.method=GET req.path=/_matrix/client/r0/sync since=s754_448 timed_out=false timeout=30s userID="@half-shot:den.half-shot.uk" user_id="@half-shot:den.half-shot.uk"
time="2020-05-10T17:53:45.289183193Z" level=info msg="Responding (693 bytes)" func="respond\n\t" file=" [/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:170]" code=200 req.id=v5cHco2LHEl6 req.method=GET req.path=/_matrix/client/r0/sync
time="2020-05-10T17:53:45.289572956Z" level=info msg=Responding func="OnIncomingSyncRequest\n\t" file=" [/build/syncapi/sync/requestpool.go:126]" next=s754_449 req.id=P9R88Q29QoDT req.method=GET req.path=/_matrix/client/r0/sync since=s754_448 timed_out=false timeout=30s userID="@half-shot:den.half-shot.uk" user_id="@half-shot:den.half-shot.uk"
time="2020-05-10T17:53:45.289645446Z" level=info msg="Responding (693 bytes)" func="respond\n\t" file=" [/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:170]" code=200 req.id=P9R88Q29QoDT req.method=GET req.path=/_matrix/client/r0/sync
time="2020-05-10T17:53:45.306831887Z" level=info msg="Incoming request" func="RequestWithLogging\n\t" file=" [/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:122]" req.id=U4FXDRlcP0Oe req.method=GET req.path=/_matrix/client/r0/sync
time="2020-05-10T17:53:45.446865595Z" level=info msg="Incoming request" func="RequestWithLogging\n\t" file=" [/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:122]" req.id=7cpm0jQGwO3k req.method=GET req.path=/_matrix/client/r0/sync
time="2020-05-10T17:53:45.499211463Z" level=info msg="Incoming request" func="RequestWithLogging\n\t" file=" [/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:122]" req.id=IUQ1xdsg2YJW req.method=GET req.path=/_matrix/client/r0/sync
time="2020-05-10T17:53:46.329824376Z" level=info msg="Incoming request" func="RequestWithLogging\n\t" file=" [/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:122]" req.id=Hnmn6Lw6yGQV req.method=PUT req.path=/_matrix/federation/v1/send/1588874602813
time="2020-05-10T17:53:46.331480157Z" level=info msg="Received transaction \"1588874602813\" containing 1 PDUs, 0 EDUs" func="Send\n\t" file=" [/build/federationapi/routing/send.go:72]" req.id=Hnmn6Lw6yGQV req.method=PUT req.path=/_matrix/federation/v1/send/1588874602813
time="2020-05-10T17:53:46.336671489Z" level=info msg="Outgoing request" func="DoHTTPRequest\n\t" file=" [/go/pkg/mod/github.com/matrix-org/gomatrixserverlib@v0.0.0-20200507150553-025991c971ea/client.go:379]" out.req.ID=2MMxSwIJN7im out.req.method=GET out.req.uri="matrix://matrix.org/_matrix/federation/v1/state_ids/%21uXDCzlYgCTHtiWCkEx:jki.re?event_id=%24HDZHXXN0rKO4UZ1pZhls8mVMdIxqcnEypLLjHvhHeNE" req.id=Hnmn6Lw6yGQV req.method=PUT req.path=/_matrix/federation/v1/send/1588874602813
time="2020-05-10T17:53:46.592603216Z" level=info msg="Outgoing request returned" func="DoHTTPRequest\n\t" file=" [/go/pkg/mod/github.com/matrix-org/gomatrixserverlib@v0.0.0-20200507150553-025991c971ea/client.go:393]" out.req.ID=2MMxSwIJN7im out.req.code=200 out.req.duration_ms=255 out.req.method=GET out.req.uri="matrix://matrix.org/_matrix/federation/v1/state_ids/%21uXDCzlYgCTHtiWCkEx:jki.re?event_id=%24HDZHXXN0rKO4UZ1pZhls8mVMdIxqcnEypLLjHvhHeNE" req.id=Hnmn6Lw6yGQV req.method=PUT req.path=/_matrix/federation/v1/send/1588874602813
time="2020-05-10T17:53:46.792998747Z" level=info msg="Incoming request" func="RequestWithLogging\n\t" file=" [/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:122]" req.id=Mj6n5vXLsucY req.method=PUT req.path=/_matrix/federation/v1/send/1588819576076
time="2020-05-10T17:53:46.793669853Z" level=info msg="Received transaction \"1588819576076\" containing 0 PDUs, 1 EDUs" func="Send\n\t" file=" [/build/federationapi/routing/send.go:72]" req.id=Mj6n5vXLsucY req.method=PUT req.path=/_matrix/federation/v1/send/1588819576076
time="2020-05-10T17:53:46.793703359Z" level=warning msg="unhandled edu" func="processEDUs\n\t" file=" [/build/federationapi/routing/send.go:225]" req.id=Mj6n5vXLsucY req.method=PUT req.path=/_matrix/federation/v1/send/1588819576076 type=m.presence
time="2020-05-10T17:53:46.793727254Z" level=info msg="Processed 0 PDUs from transaction \"1588819576076\"" func="processTransaction\n\t" file=" [/build/federationapi/routing/send.go:186]" req.id=Mj6n5vXLsucY req.method=PUT req.path=/_matrix/federation/v1/send/1588819576076
time="2020-05-10T17:53:46.793757818Z" level=info msg="Responding (11 bytes)" func="respond\n\t" file=" [/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:170]" code=200 req.id=Mj6n5vXLsucY req.method=PUT req.path=/_matrix/federation/v1/send/1588819576076
time="2020-05-10T17:53:46.893665173Z" level=info msg="Fetching missing state at event" func="lookupMissingStateViaStateIDs\n\t" file=" [/build/federationapi/routing/send.go:405]" already_have=556 event_id="$HDZHXXN0rKO4UZ1pZhls8mVMdIxqcnEypLLjHvhHeNE" missing=0 req.id=Hnmn6Lw6yGQV req.method=PUT req.path=/_matrix/federation/v1/send/1588874602813 room_id="!uXDCzlYgCTHtiWCkEx:jki.re" total_auth_events=391 total_state=193
time="2020-05-10T17:53:46.894190295Z" level=info msg="Checking event signatures for 584 events of room state" func="Check\n\t" file=" [/go/pkg/mod/github.com/matrix-org/gomatrixserverlib@v0.0.0-20200507150553-025991c971ea/federationtypes.go:375]" req.id=Hnmn6Lw6yGQV req.method=PUT req.path=/_matrix/federation/v1/send/1588874602813
time="2020-05-10T17:53:47.212794945Z" level=error msg="Request panicked!\ngoroutine 147337 [running]:\nruntime/debug.Stack(0xc00012a0e0, 0xc000f4c2d0, 0xc00012a150)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/matrix-org/util.Protect.func1.1(0xc000eb6a00, 0x1098680, 0xc000bbdea0)\n\t/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:98 +0x15d\npanic(0xddbce0, 0x165dfd0)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ngithub.com/matrix-org/gomatrixserverlib.(*Event).Sender(0x0, 0xc0006be600, 0xc0002b70d8)\n\t/go/pkg/mod/github.com/matrix-org/gomatrixserverlib@v0.0.0-20200507150553-025991c971ea/event.go:743 +0x3a\ngithub.com/matrix-org/dendrite/roomserver/internal.updateToLeaveMembership(0x10a63c0, 0xc001347b80, 0x0, 0xf04ff0, 0x5, 0x0, 0x0, 0x0, 0x1, 0x0, ...)\n\t/build/roomserver/internal/input_membership.go:207 +0x68\ngithub.com/matrix-org/dendrite/roomserver/internal.updateMembership(0x10aa3a0, 0xc0005cc060, 0x10004, 0xc0012536c8, 0x0, 0x0, 0x0, 0x0, 0x3, 0x0, ...)\n\t/build/roomserver/internal/input_membership.go:120 +0x162\ngithub.com/matrix-org/dendrite/roomserver/internal.updateMemberships(0x109c500, 0xc0000c2058, 0x10b6620, 0xc00011a700, 0x10aa3a0, 0xc0005cc060, 0xc00054a0c0, 0x4, 0x4, 0xc000ea1280, ...)\n\t/build/roomserver/internal/input_membership.go:74 +0x274\ngithub.com/matrix-org/dendrite/roomserver/internal.(*latestEventsUpdater).doUpdateLatestEvents(0xc000f4cdb0, 0x109c500, 0xc0000c2058)\n\t/build/roomserver/internal/input_latest_events.go:150 +0x468\ngithub.com/matrix-org/dendrite/roomserver/internal.updateLatestEvents(0x109c500, 0xc0000c2058, 0x10b6620, 0xc00011a700, 0x1084e40, 0xc0002697a0, 0x2, 0x210, 0x10003, 0x0, ...)\n\t/build/roomserver/internal/input_latest_events.go:76 +0x293\ngithub.com/matrix-org/dendrite/roomserver/internal.processRoomEvent(0x109c500, 0xc0000c2058, 0x10b6620, 0xc00011a700, 0x1084e40, 0xc0002697a0, 0x2, 0x167dd15, 0x1, 0x0, ...)\n\t/build/roomserver/internal/input_events.go:97 +0x640\ngithub.com/matrix-org/dendrite/roomserver/internal.(*RoomserverInternalAPI).InputRoomEvents(0xc0002697a0, 0x109c500, 0xc0000c2058, 0xc000fcfef0, 0xc0004c9470, 0x0, 0x0)\n\t/build/roomserver/internal/input.go:74 +0x41c\ngithub.com/matrix-org/dendrite/clientapi/producers.(*RoomserverProducer).SendInputRoomEvents(0xc00037cf90, 0x109c500, 0xc0000c2058, 0xc000503080, 0x1, 0x1, 0x0, 0x1, 0xc0013b2000, 0x22c)\n\t/build/clientapi/producers/roomserver.go:100 +0xc6\ngithub.com/matrix-org/dendrite/clientapi/producers.(*RoomserverProducer).SendEventWithState(0xc00037cf90, 0x109c500, 0xc0000c2058, 0xc000b53480, 0x167dd15, 0x1, 0x0, 0xc0005d0600, 0x5e2, 0x600, ...)\n\t/build/clientapi/producers/roomserver.go:90 +0x460\ngithub.com/matrix-org/dendrite/federationapi/routing.(*txnReq).processEventWithMissingState(0xc000f4f2a0, 0x0, 0xc0005d0600, 0x5e2, 0x600, 0xe45d60, 0xc000f042a0, 0x167dd15, 0x1, 0x167dd15, ...)\n\t/build/federationapi/routing/send.go:346 +0x4d0\ngithub.com/matrix-org/dendrite/federationapi/routing.(*txnReq).processEvent(0xc000e792a0, 0x0, 0xc0005d0600, 0x5e2, 0x600, 0xe45d60, 0xc000f042a0, 0x167dd15, 0x1, 0xe45d60, ...)\n\t/build/federationapi/routing/send.go:256 +0x861\ngithub.com/matrix-org/dendrite/federationapi/routing.(*txnReq).processTransaction(0xc000f4f2a0, 0x4, 0xf32552, 0x33)\n\t/build/federationapi/routing/send.go:151 +0x219\ngithub.com/matrix-org/dendrite/federationapi/routing.Send(0xc000eb6b00, 0xc0005731a0, 0xc000e5ebe0, 0xd, 0xc000127400, 0x10b0820, 0xc0002697a0, 0xc00037cf90, 0xc00037cf80, 0xc00021e5e0, ...)\n\t/build/federationapi/routing/send.go:74 +0x3d3\ngithub.com/matrix-org/dendrite/federationapi/routing.Setup.func2(0xc000eb6b00, 0xc0005731a0, 0xa2cb5eeb854b, 0x16b2820, 0xc0000c30a0, 0x10)\n\t/build/federationapi/routing/routing.go:80 +0x20d\ngithub.com/matrix-org/dendrite/common.MakeFedAPI.func1(0xc000eb6b00, 0x0, 0x0, 0x0, 0x0)\n\t/build/common/httpapi.go:180 +0x15f\ngithub.com/matrix-org/util.(*jsonRequestHandlerWrapper).OnIncomingRequest(0xc0000c4a30, 0xc000eb6b00, 0xc0006e1320, 0x30, 0x30, 0xe7a7c0)\n\t/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:79 +0x33\ngithub.com/matrix-org/util.MakeJSONAPI.func1(0x1098680, 0xc000bbdea0, 0xc000eb6b00)\n\t/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:139 +0x97\ngithub.com/matrix-org/util.Protect.func1(0x1098680, 0xc000bbdea0, 0xc000eb6a00)\n\t/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:103 +0xa1\nnet/http.HandlerFunc.ServeHTTP(...)\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/matrix-org/dendrite/common.MakeExternalAPI.func1(0x1098680, 0xc000bbdea0, 0xc000eb6900)\n\t/build/common/httpapi.go:106 +0x22b\nnet/http.HandlerFunc.ServeHTTP(0xc00039f9b0, 0x1098680, 0xc000bbdea0, 0xc000eb6900)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc0001cc180, 0x1098680, 0xc000bbdea0, 0xc000eb6700)\n\t/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2\ngithub.com/matrix-org/dendrite/common.WrapHandlerInCORS.func1(0x1098680, 0xc000bbdea0, 0xc000eb6700)\n\t/build/common/httpapi.go:231 +0x340\nnet/http.HandlerFunc.ServeHTTP(0xc00021e480, 0x1098680, 0xc000bbdea0, 0xc000eb6700)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\nnet/http.(*ServeMux).ServeHTTP(0x16b2620, 0x1098680, 0xc000bbdea0, 0xc000eb6700)\n\t/usr/local/go/src/net/http/server.go:2387 +0x1bd\nnet/http.serverHandler.ServeHTTP(0xc000162000, 0x1098680, 0xc000bbdea0, 0xc000eb6700)\n\t/usr/local/go/src/net/http/server.go:2802 +0xa4\nnet/http.(*conn).serve(0xc000cc0640, 0x109c4c0, 0xc000bb8a00)\n\t/usr/local/go/src/net/http/server.go:1890 +0x875\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2928 +0x384\n" func="1\n\t" file=" [/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:97]" context=missing panic="runtime error: invalid memory address or nil pointer dereference"
time="2020-05-10T17:53:47.213088999Z" level=info msg="Responding (35 bytes)" func="respond\n\t" file=" [/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:170]" code=500 context=missing
time="2020-05-10T17:53:47.343166895Z" level=info msg="Outgoing request returned" func="DoHTTPRequest\n\t" file=" [/go/pkg/mod/github.com/matrix-org/gomatrixserverlib@v0.0.0-20200507150553-025991c971ea/client.go:393]" out.req.ID=KS6Ga2AeJGE5 out.req.code=200 out.req.duration_ms=2234 out.req.method=GET out.req.uri="matrix://maunium.net/_matrix/federation/v1/state_ids/%21uXDCzlYgCTHtiWCkEx:jki.re?event_id=%24cMDQv6ZtqSKHxLBkog4-Yyt2Lek8QE17EH26QqIa8jM" req.id=s4bEuVkzR6rj req.method=PUT req.path=/_matrix/federation/v1/send/1589078461993
time="2020-05-10T17:53:47.620219804Z" level=info msg="Fetching missing state at event" func="lookupMissingStateViaStateIDs\n\t" file=" [/build/federationapi/routing/send.go:405]" already_have=558 event_id="$cMDQv6ZtqSKHxLBkog4-Yyt2Lek8QE17EH26QqIa8jM" missing=0 req.id=s4bEuVkzR6rj req.method=PUT req.path=/_matrix/federation/v1/send/1589078461993 room_id="!uXDCzlYgCTHtiWCkEx:jki.re" total_auth_events=393 total_state=194
time="2020-05-10T17:53:47.621160104Z" level=info msg="Checking event signatures for 587 events of room state" func="Check\n\t" file=" [/go/pkg/mod/github.com/matrix-org/gomatrixserverlib@v0.0.0-20200507150553-025991c971ea/federationtypes.go:375]" req.id=s4bEuVkzR6rj req.method=PUT req.path=/_matrix/federation/v1/send/1589078461993
time="2020-05-10T17:53:47.946260025Z" level=error msg="Request panicked!\ngoroutine 147303 [running]:\nruntime/debug.Stack(0xc0003522a0, 0xc000ddc2d0, 0xc000352380)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/matrix-org/util.Protect.func1.1(0xc000ca0300, 0x1098680, 0xc000bf8a80)\n\t/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:98 +0x15d\npanic(0xddbce0, 0x165dfd0)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ngithub.com/matrix-org/gomatrixserverlib.(*Event).Sender(0x0, 0xc000c50400, 0xc0003afd78)\n\t/go/pkg/mod/github.com/matrix-org/gomatrixserverlib@v0.0.0-20200507150553-025991c971ea/event.go:743 +0x3a\ngithub.com/matrix-org/dendrite/roomserver/internal.updateToLeaveMembership(0x10a63c0, 0xc000ebe640, 0x0, 0xf04ff0, 0x5, 0x0, 0x0, 0x0, 0x1, 0x0, ...)\n\t/build/roomserver/internal/input_membership.go:207 +0x68\ngithub.com/matrix-org/dendrite/roomserver/internal.updateMembership(0x10aa3a0, 0xc000c44000, 0x10043, 0xc000c50320, 0x0, 0x0, 0x0, 0x0, 0x2, 0x0, ...)\n\t/build/roomserver/internal/input_membership.go:120 +0x162\ngithub.com/matrix-org/dendrite/roomserver/internal.updateMemberships(0x109c500, 0xc0000c2058, 0x10b6620, 0xc00011a700, 0x10aa3a0, 0xc000c44000, 0xc00107a270, 0x2, 0x2, 0x0, ...)\n\t/build/roomserver/internal/input_membership.go:74 +0x274\ngithub.com/matrix-org/dendrite/roomserver/internal.(*latestEventsUpdater).doUpdateLatestEvents(0xc000ddcdb0, 0x109c500, 0xc0000c2058)\n\t/build/roomserver/internal/input_latest_events.go:150 +0x468\ngithub.com/matrix-org/dendrite/roomserver/internal.updateLatestEvents(0x109c500, 0xc0000c2058, 0x10b6620, 0xc00011a700, 0x1084e40, 0xc0002697a0, 0x2, 0x212, 0x1000b, 0x0, ...)\n\t/build/roomserver/internal/input_latest_events.go:76 +0x293\ngithub.com/matrix-org/dendrite/roomserver/internal.processRoomEvent(0x109c500, 0xc0000c2058, 0x10b6620, 0xc00011a700, 0x1084e40, 0xc0002697a0, 0x2, 0x167dd15, 0x1, 0x0, ...)\n\t/build/roomserver/internal/input_events.go:97 +0x640\ngithub.com/matrix-org/dendrite/roomserver/internal.(*RoomserverInternalAPI).InputRoomEvents(0xc0002697a0, 0x109c500, 0xc0000c2058, 0xc00084bec0, 0xc0010bde90, 0x0, 0x0)\n\t/build/roomserver/internal/input.go:74 +0x41c\ngithub.com/matrix-org/dendrite/clientapi/producers.(*RoomserverProducer).SendInputRoomEvents(0xc00037cf90, 0x109c500, 0xc0000c2058, 0xc000f89130, 0x1, 0x1, 0x0, 0x1, 0xc001136000, 0x22e)\n\t/build/clientapi/producers/roomserver.go:100 +0xc6\ngithub.com/matrix-org/dendrite/clientapi/producers.(*RoomserverProducer).SendEventWithState(0xc00037cf90, 0x109c500, 0xc0000c2058, 0xc0012cc040, 0x167dd15, 0x1, 0x0, 0xc000bca300, 0x2f9, 0x300, ...)\n\t/build/clientapi/producers/roomserver.go:90 +0x460\ngithub.com/matrix-org/dendrite/federationapi/routing.(*txnReq).processEventWithMissingState(0xc000ddf2a0, 0x0, 0xc000bca300, 0x2f9, 0x300, 0xe45d60, 0xc000bf8e00, 0x167dd15, 0x1, 0x167dd15, ...)\n\t/build/federationapi/routing/send.go:346 +0x4d0\ngithub.com/matrix-org/dendrite/federationapi/routing.(*txnReq).processEvent(0xc000e792a0, 0x0, 0xc000bca300, 0x2f9, 0x300, 0xe45d60, 0xc000bf8e00, 0x167dd15, 0x1, 0xe45d60, ...)\n\t/build/federationapi/routing/send.go:256 +0x861\ngithub.com/matrix-org/dendrite/federationapi/routing.(*txnReq).processTransaction(0xc000ddf2a0, 0x4, 0xf32552, 0x33)\n\t/build/federationapi/routing/send.go:151 +0x219\ngithub.com/matrix-org/dendrite/federationapi/routing.Send(0xc000ca0400, 0xc000c45740, 0xc00108a9a0, 0xd, 0xc000127400, 0x10b0820, 0xc0002697a0, 0xc00037cf90, 0xc00037cf80, 0xc00021e5e0, ...)\n\t/build/federationapi/routing/send.go:74 +0x3d3\ngithub.com/matrix-org/dendrite/federationapi/routing.Setup.func2(0xc000ca0400, 0xc000c45740, 0xa2cb15273486, 0x16b2820, 0xc0000c30a0, 0x10)\n\t/build/federationapi/routing/routing.go:80 +0x20d\ngithub.com/matrix-org/dendrite/common.MakeFedAPI.func1(0xc000ca0400, 0x0, 0x0, 0x0, 0x0)\n\t/build/common/httpapi.go:180 +0x15f\ngithub.com/matrix-org/util.(*jsonRequestHandlerWrapper).OnIncomingRequest(0xc0000c4a30, 0xc000ca0400, 0xc000c0f5f0, 0x30, 0x30, 0xe7a7c0)\n\t/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:79 +0x33\ngithub.com/matrix-org/util.MakeJSONAPI.func1(0x1098680, 0xc000bf8a80, 0xc000ca0400)\n\t/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:139 +0x97\ngithub.com/matrix-org/util.Protect.func1(0x1098680, 0xc000bf8a80, 0xc000ca0300)\n\t/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:103 +0xa1\nnet/http.HandlerFunc.ServeHTTP(...)\n\t/usr/local/go/src/net/http/server.go:2007\ngithub.com/matrix-org/dendrite/common.MakeExternalAPI.func1(0x1098680, 0xc000bf8a80, 0xc000ca0200)\n\t/build/common/httpapi.go:106 +0x22b\nnet/http.HandlerFunc.ServeHTTP(0xc00039f9b0, 0x1098680, 0xc000bf8a80, 0xc000ca0200)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\ngithub.com/gorilla/mux.(*Router).ServeHTTP(0xc0001cc180, 0x1098680, 0xc000bf8a80, 0xc000ca0000)\n\t/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2\ngithub.com/matrix-org/dendrite/common.WrapHandlerInCORS.func1(0x1098680, 0xc000bf8a80, 0xc000ca0000)\n\t/build/common/httpapi.go:231 +0x340\nnet/http.HandlerFunc.ServeHTTP(0xc00021e480, 0x1098680, 0xc000bf8a80, 0xc000ca0000)\n\t/usr/local/go/src/net/http/server.go:2007 +0x44\nnet/http.(*ServeMux).ServeHTTP(0x16b2620, 0x1098680, 0xc000bf8a80, 0xc000ca0000)\n\t/usr/local/go/src/net/http/server.go:2387 +0x1bd\nnet/http.serverHandler.ServeHTTP(0xc000162000, 0x1098680, 0xc000bf8a80, 0xc000ca0000)\n\t/usr/local/go/src/net/http/server.go:2802 +0xa4\nnet/http.(*conn).serve(0xc000c86dc0, 0x109c4c0, 0xc0005fb180)\n\t/usr/local/go/src/net/http/server.go:1890 +0x875\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2928 +0x384\n" func="1\n\t" file=" [/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:97]" context=missing panic="runtime error: invalid memory address or nil pointer dereference"
time="2020-05-10T17:53:47.946372645Z" level=info msg="Responding (35 bytes)" func="respond\n\t" file=" [/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:170]" code=500 context=missing
```

### PR DESCRIPTION
**Pull request by neilalexander**
This sorta fixes #1016.

### CODE REVIEW

File: roomserver/internal/input_membership.go [hunk 1]
```diff
@@ -106,6 +107,13 @@ func updateMembership(
 		return updates, nil
 	}
 
+	if add == nil {
```
Comment (Kegsay) [inline roomserver/internal/input_membership.go:110]: Looking at the comments, `add==nil` if its a leave, as:

```
// Default the membership to Leave if no event was added or removed.
oldMembership := gomatrixserverlib.Leave
newMembership := gomatrixserverlib.Leave
```

Comment (neilalexander) [reply roomserver/internal/input_membership.go:110]: But in that case it should be that the old membership is whatever it was before and the new membership is now `leave`. If it's old `leave` and new `leave` then we should have filtered that out in the check above it.
