### PR TITLE
syncapi: Rename and split out tokens

### LINKED ISSUE #1015: /sync panics after joining a room
I joined `!XKjkxFMpKwcGmVfsvN:cadair.com`, however ever since the sync has been panicing. The panic line is:

```
time="2020-05-08T15:17:41.824953851Z" level=error msg="Request panicked!
goroutine 316 [running]:
runtime/debug.Stack(0xc0001040e0, 0xc0005e1dc8, 0xc0001041c0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/matrix-org/util.Protect.func1.1(0xc000130500, 0x1098440, 0xc0001442a0)
	/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:98 +0x15d
panic(0xe85ce0, 0xc0000360e0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/matrix-org/dendrite/syncapi/storage/postgres.(*SyncServerDatasource).getResponseWithPDUsForCompleteSync(0xc0001a5680, 0x109c340, 0xc0003d13b0, 0xc00064e3a0, 0x1b, 0x14, 0xc000644240, 0x0, 0x0, 0x23e, ...)
	/build/syncapi/storage/postgres/syncserver.go:590 +0xbf5
github.com/matrix-org/dendrite/syncapi/storage/postgres.(*SyncServerDatasource).CompleteSync(0xc0001a5680, 0x109c340, 0xc0003d13b0, 0xc00064e3a0, 0x1b, 0x14, 0xf078af, 0x7, 0xc0001a49e8)
	/build/syncapi/storage/postgres/syncserver.go:622 +0x81
github.com/matrix-org/dendrite/syncapi/sync.(*RequestPool).currentSyncForUser(0xc000185410, 0x109c340, 0xc0003d13b0, 0xc00036c2b8, 0x8, 0xc00064e3a0, 0x1b, 0xc0003f8407, 0x2b, 0x8, ...)
	/build/syncapi/sync/requestpool.go:138 +0x376
github.com/matrix-org/dendrite/syncapi/sync.(*RequestPool).OnIncomingSyncRequest(0xc000185410, 0xc000130700, 0xc0000c82d0, 0x0, 0x0, 0x0, 0x0)
	/build/syncapi/sync/requestpool.go:67 +0x40c
github.com/matrix-org/dendrite/syncapi/routing.Setup.func1(0xc000130700, 0xc0000c82d0, 0xd8a100, 0x106f3d0, 0xef7f20, 0xc00018c850)
	/build/syncapi/routing/routing.go:56 +0x3e
github.com/matrix-org/dendrite/common.MakeAuthAPI.func1(0xc000130600, 0x0, 0x0, 0x0, 0x0)
	/build/common/httpapi.go:46 +0x325
github.com/matrix-org/util.(*jsonRequestHandlerWrapper).OnIncomingRequest(0xc000010090, 0xc000130600, 0xc0003d0d20, 0x30, 0x30, 0xe7a7c0)
	/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:79 +0x33
github.com/matrix-org/util.MakeJSONAPI.func1(0x1098440, 0xc0001442a0, 0xc000130600)
	/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:139 +0x97
github.com/matrix-org/util.Protect.func1(0x1098440, 0xc0001442a0, 0xc000130500)
	/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:103 +0xa1
net/http.HandlerFunc.ServeHTTP(...)
	/usr/local/go/src/net/http/server.go:2007
github.com/matrix-org/dendrite/common.MakeExternalAPI.func1(0x1098440, 0xc0001442a0, 0xc000130400)
	/build/common/httpapi.go:106 +0x22b
net/http.HandlerFunc.ServeHTTP(0xc000230240, 0x1098440, 0xc0001442a0, 0xc000130400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00018a240, 0x1098440, 0xc0001442a0, 0xc000130100)
	/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2
github.com/matrix-org/dendrite/common.WrapHandlerInCORS.func1(0x1098440, 0xc0001442a0, 0xc000130100)
	/build/common/httpapi.go:231 +0x340
net/http.HandlerFunc.ServeHTTP(0xc00024ea60, 0x1098440, 0xc0001442a0, 0xc000130100)
	/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.(*ServeMux).ServeHTTP(0x16b1620, 0x1098440, 0xc0001442a0, 0xc000130100)
	/usr/local/go/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc000148000, 0x1098440, 0xc0001442a0, 0xc000130100)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc000273720, 0x109c280, 0xc0005da140)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2928 +0x384
" func="1
	" file=" [/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:97]" context=missing panic="runtime error: index out of range [0] with length 0"
```

I have verified that this is the room causing the panic

### PR DESCRIPTION
**Pull request by Kegsay**
Previously we used the badly named `PaginationToken` which was
used for both `/sync` and `/messages` requests. This quickly
became confusing because named fields like `PDUPosition` meant
different things depending on the token type. Instead, we now have
two token types: `TopologyToken` and `StreamingToken`, both of
which have fields which make more sense for their specific situations.

Updated the codebase to use one or the other. `PaginationToken` still
lives on as `syncToken`, an unexported type which both tokens rely on.
This allows us to guarantee that the specific mappings of positions
to a string remain solely under the control of the `types` package.
This enables us to move high-level conceptual things like
"decrement this topological token" to function calls e.g
`TopologicalToken.Decrement()`.

This does not fix #1015 yet.

### CODE REVIEW

File: syncapi/types/types.go [hunk 1]
```diff
@@ -27,138 +27,213 @@ import (
...
-	token = new(PaginationToken)
+	token = new(syncToken)
 	var positions []string
 
-	switch t := PaginationTokenType(s[:1]); t {
-	case PaginationTokenTypeStream, PaginationTokenTypeTopology:
+	switch t := SyncTokenType(s[:1]); t {
+	case SyncTokenTypeStream, SyncTokenTypeTopology:
 		token.Type = t
 		positions = strings.Split(s[1:], "_")
```
Comment (neilalexander) [inline syncapi/types/types.go:154]: It doesn't appear as if we guard anywhere against the sync token containing no positions, which becomes a problem later on in `Depth()`, `PDUPosition()` and `EDUPosition()` etc where we index on specific array indices. That could result in panics, so it's probably best to make sure we check that we get at least the number of expected positions *somewhere*.

**Comment by Kegsay** [comment]
`run-tests PASSED`
