### PR TITLE
Return `null` if MaxFileSizeBytes is 0

### LINKED ISSUE #2408: max_file_size_bytes = 0 counts as limited file size
### Background information

- **Dendrite version or git SHA**: 0.8.2
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: Yes
- **`go version`**: -
- **Client used (if applicable)**: Element Web

### Description

 - **What** is the problem:
When `max_file_size_bytes` to `0`, uploading file doesn't count as unlimited as intended. Fetching file from other servers counts as unlimited.

 - **Who** is affected: -
 - **How** is this bug manifesting:
 

 - **When** did this first appear:
Set `max_file_size_bytes` to `0` in `dendrite.yaml` config file

### Steps to reproduce

- Set `max_file_size_bytes` to `0` in `dendrite.yaml` config file
- Restart the server
- Try to upload the file

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

### PR DESCRIPTION
**Pull request by S7evinK**
This should fix #2408.

> The maximum size an upload can be in bytes. Clients SHOULD use this as a guide when uploading content. If not listed or null, the size limit should be treated as unknown.

### CODE REVIEW

File: mediaapi/routing/routing.go [hunk 1]
```diff
@@ -73,9 +73,13 @@ func Setup(
 		if r := rateLimits.Limit(req); r != nil {
 			return *r
 		}
+		respondSize := cfg.MaxFileSizeBytes
+		if *cfg.MaxFileSizeBytes == 0 {
```
Comment (neilalexander) [inline mediaapi/routing/routing.go:77]: Need to check not `nil` here also to avoid a potential panic.

**Review by neilalexander — CHANGES_REQUESTED** [review]

File: mediaapi/routing/routing.go (hunk 1 above)
Comment (S7evinK) [reply mediaapi/routing/routing.go:77]: That should be done at startup, will add a comment.

Comment (neilalexander) [reply mediaapi/routing/routing.go]: If it can't be `nil`, why is it a pointer type to begin with? :-) Let's simplify that.

**Review by neilalexander — APPROVED** [review]
