### PR TITLE
Bug fix #2718 appservice txnid should be different for each batch of events

### LINKED ISSUE #2718: Appservice incorrectly handling a batch of events with the same transaction ID
### Background information

- **Dendrite version or git SHA**: 0ea948c70548875601a544c57a588271af3adce4 (latest main on 9/14)
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: SQLite3
- **Running in Docker?**: No
- **`go version`**: go version go1.19 darwin/amd64
- **Client used (if applicable)**:

### Description
 - **What** is the problem:

I am seeing a regression with appservice. I am working on an appservice that uses the matrix-bot-sdk. My appservice was working prior to this PR that was merged: [Refactor appservices component](https://github.com/matrix-org/dendrite/pull/2687)

Before the PR was merged, my appservice is able to see all events associated with a new space/ room creation. When a space is created, it was able to see all the related events - room.create, room.join, etc. After pulling the latest main, the appservice is no longer able to see the events when a space is created.

I traced it to this logic in appservice/consumers/roomserver.go. In line 178 of the func sendEvents( ... ):

`txnID := events[0].Event.OriginServerTS()`

What's happening is that the batch of events associated with space / room creation has the same OriginServerTS(). Dendrite sends the first event to the appservice. The appservice processes the event, and completes the transaction. The sendEvents func is invoked again with the rest of the events. The txnID is exactly the same as before. Consequently, the appservice thinks that this transaction has been processed, and ignores the events.

 - **Who** is affected:
I am building on matrix-bot-sdk. This regression could affect any projects using that sdk. Didn't try other appservice sdk. 

 - **How** is this bug manifesting:
Configure an appservice (based on matrix-bot-sdk). Create a space or a room. Appservice no longer gets all the associated events with creating the room.

 - **When** did this first appear:
After this PR was merged: [Refactor appservices component](https://github.com/matrix-org/dendrite/pull/2687)

I will create a PR for fixing it. Will gather feedback in the PR.

### PR DESCRIPTION
**Pull request by tak-hntlabs**
See issue: [#2718](https://github.com/matrix-org/dendrite/issues/2718) for more details.

The fix assumes that if the number of transaction items are different, then the txnid should be different. 

txnid := OriginalServerTS()_len(transactions) 

The case that it doesn't address is if the txnid generated this way is the same for 2 different batches of events which have the same OriginalServerTS and the same array length.

Another option:

txnid := OriginalServerTS()_hash(transactions)

Would love to hear other ideas and ways to fix this.

### Pull Request Checklist

* [x ] I have added added tests for PR _or_ I have justified why this PR doesn't need tests.
* [x ] Pull request includes a [sign off](https://github.com/matrix-org/dendrite/blob/main/docs/CONTRIBUTING.md#sign-off)

Signed-off-by: `Tak Wai Wong <tak@hntlabs.com>`

### CODE REVIEW

**Comment by S7evinK** [comment]
As the `TODO` mentions, I'd probably also go for the NATS timestamp, something like 

```go
// If the number of items in the array is different,
// then this should be treated as a different transaction. Incorporate the length
// of events into the transaction ID.
txnID := fmt.Sprintf("%d_%d", events[0].Event.OriginServerTS(), len(events))
// Try to get the message metadata, if we're able to, use the timestamp as the txnID
metadata, err := msgs[0].Metadata()
if err == nil {
	txnID = strconv.Itoa(int(metadata.Timestamp.Unix()))
}
// Send event to any relevant application services. If we hit
// an error here, return false, so that we negatively ack.
return s.sendEvents(ctx, state, events, txnID) == nil
```
in `onMessage`

**Comment by tak-hntlabs** [comment]
> As the `TODO` mentions, I'd probably also go for the NATS timestamp, something like
> 
> ```go
> // If the number of items in the array is different,
> // then this should be treated as a different transaction. Incorporate the length
> // of events into the transaction ID.
> txnID := fmt.Sprintf("%d_%d", events[0].Event.OriginServerTS(), len(events))
> // Try to get the message metadata, if we're able to, use the timestamp as the txnID
> metadata, err := msgs[0].Metadata()
> if err == nil {
> 	txnID = strconv.Itoa(int(metadata.Timestamp.Unix()))
> }
> // Send event to any relevant application services. If we hit
> // an error here, return false, so that we negatively ack.
> return s.sendEvents(ctx, state, events, txnID) == nil
> ```
> 
> in `onMessage`

what is msgs[0].Metadata() ? I don't see anything like that in the sendEvents function.

**Comment by S7evinK** [comment]
> what is msgs[0].Metadata() ? I don't see anything like that in the sendEvents function.

That's in `onMessage`, the metadata of a NATS message. With my example `sendEvents` would get an additional parameter `txnID`, and the end of `onMessage` (after the `if len(events) == 0`-check) would become the example.

**Comment by tak-hntlabs** [comment]
> That's in `onMessage`, the metadata of a NATS message. With my example `sendEvents` would get an additional parameter `txnID`, and the end of `onMessage` (after the `if len(events) == 0`-check) would become the example.

that worked! Thanks!

File: appservice/consumers/roomserver.go [hunk 1]
```diff
@@ -151,15 +152,25 @@ func (s *OutputRoomEventConsumer) onMessage(
 		return true
 	}
 
+	txnID := ""
```
Comment (S7evinK) [inline appservice/consumers/roomserver.go:155]: `msgs` can't be 0 at this point, we already iterated over them and did a `len(events) == 0` check before. So this can be removed.
I'd prefer having
```go
txnID := fmt.Sprintf("%d_%d", events[0].Event.OriginServerTS(), len(transaction))
```
from `sendEvents` here (instead of `txnID := ""`), so it's easier to read.

File: appservice/consumers/roomserver.go [hunk 2]
```diff
@@ -151,15 +152,25 @@ func (s *OutputRoomEventConsumer) onMessage(
...
 	// an error here, return false, so that we negatively ack.
 	log.WithField("appservice", state.ID).Debugf("Appservice worker sending %d events(s) from roomserver", len(events))
-	return s.sendEvents(ctx, state, events) == nil
+	return s.sendEvents(txnID, ctx, state, events) == nil
 }
 
 // sendEvents passes events to the appservice by using the transactions
 // endpoint. It will block for the backoff period if necessary.
 func (s *OutputRoomEventConsumer) sendEvents(
+	txnID string,
```
Comment (S7evinK) [inline appservice/consumers/roomserver.go:173]: Can you move the new parameter to the end?
Having `context.Context` as the first parameter is more idiomatic Go.

**Review by S7evinK — CHANGES_REQUESTED** [review]
Besides the comments, I'm happy with this. :)

File: appservice/consumers/roomserver.go (hunk 2 above)
Comment (tak-hntlabs) [reply appservice/consumers/roomserver.go:173]: done.

File: appservice/consumers/roomserver.go (hunk 1 above)
Comment (S7evinK) [reply appservice/consumers/roomserver.go:155]: Fair enough.

**Review by S7evinK — APPROVED** [review]

**Comment by S7evinK** [comment]
Thanks for this!
