### PR TITLE
Fix bugs related to state resolution

### LINKED ISSUE #2129: m.room.power_levels event missing from some rooms
### Background information

- **Dendrite version or git SHA**: 0.6
- **Monolith or Polylith?**: monolith
- **SQLite3 or Postgres?**: postgres
- **Running in Docker?**: no
- **`go version`**: 1.17.6
- **Client used (if applicable)**: Element

### Description

 - **What** is the problem: lack of any m.room.power_levels event in a specific public room (v6)
 - **Who** is affected: user accounts on the dendrite homeserver
 - **How** is this bug manifesting: No power levels or permissions can be viewed or changed with accounts on the dendrite homeserver, but with a matrix.org account the room looks normal.
 - **When** did this first appear: after the 0.5.1 -> 0.6 upgrade

When I load the room in question I don't see any errors logged, not even a warn.  
There's a lot of `superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:65)` but that happens for every room.  
Haven't found any relevant errors in Element either.

### Steps to reproduce

I haven't found a way to reproduce this, apart from join this specific room with an account on its homeserver.  
The room is the only one with some users banned, but I tried creating a new room (on the same homeserver), joining it with a matrix.org account, banning that account - but no issue found.

Possibly something in the database was lost during the upgrade?

Edit2: the room's federation is not broken, other events are federating (in both directions).  
Can we reset something to make it get the power levels from matrix.org?

### LINKED ISSUE #2465: State of #dendrite:matrix.org is broken
### Background information

- **Dendrite version or git SHA**: 0.8.5
- **Monolith or Polylith?**: monolith
- **SQLite3 or Postgres?**: postgres
- **Running in Docker?**: no
- **`go version`**: 1.17.9
- **Client used (if applicable)**: Element web

### Description

 - **What** is the problem: Dendrite's view of the room differs hugely from matrix.org's view, to the point that it's unusable.  It considers the room to be invite-only, so it rejects the joins and messages of all users who joined after the room was (temporarily) invite only.  It considers @neilalexander:dendrite.matrix.org to not be in the room.
 - **Who** is affected:
 - **How** is this bug manifesting:
 - **When** did this first appear: it has never worked properly, but is worse than it used to be

### Steps to reproduce

Other Dendrite users have reported a similar problem in chat, including that other users on their homeserver cannot join the room.
Possibly related to #2129

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

### LINKED ISSUE #2503: Clear cache & reload breaks membership in rooms suggested by a Space in (only) Element Web
### Background information

- **Dendrite version or git SHA**: 0.8.6
- **Monolith or Polylith?**: monolith
- **SQLite3 or Postgres?**: postgres
- **Running in Docker?**: no
- **`go version`**: 1.17.9
- **Client used (if applicable)**: element web, element android

### Description

 - **What** is the problem: room membership changes and becomes inconsistent, seemingly at random, when updating and/or restarting
 - **Who** is affected: 
 - **How** is this bug manifesting: element web shows I am no longer in some rooms, and cannot access the room when trying to rejoin, but in element android I am still able to participate in the same rooms.  Additionally, the server reverts to participating in the old #dendrite room, requiring evacuateRoom to be used again.
 - **When** did this first appear: unknown

### Steps to reproduce

- update and/or restart dendrite, observe that membership has changed and is now inconsistent between clients
- clearing cache and/or re-logging has no effect

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

When trying to "re"-join the rooms in element web, dendrite will log a successful room join, but the spinner continues endlessly in element web, and when refreshing it's back to showing the room as not joined.  The options seem to be:  
- access the room using element android only
- leave the room using `curl` or element android, and re-join it

These are all public v6 rooms.

When the errors for the old #dendrite start being logged again, I check the state in element web and it shows I'm both in the room (listed in the user list) and not in the room (room is being previewed, with a button to join).  
When I do `GET /_dendrite/admin/evacuateRoom/!yomrOFwgFXzmeMAbzX:matrix.org`  
it returns `{"affected":["@bones_was_here:xonotic.org"]}`  
and on a second GET it returns the empty array (until the next time it reverts).

### PR DESCRIPTION
**Pull request by neilalexander**
This should hopefully fix a bunch of seemingly random state corruption issues that were happening.

Should fix #2503, fix #2465, fix #2129.

### CODE REVIEW

File: roomserver/state/state.go [hunk 1]
```diff
@@ -996,6 +971,42 @@ func (v *StateResolution) loadStateEvents(
 	return result, eventIDMap, nil
 }
 
+// loadAuthEvents loads all of the auth events for a given event recursively.
+func (v *StateResolution) loadAuthEvents(
+	ctx context.Context, event *gomatrixserverlib.Event,
+) ([]*gomatrixserverlib.Event, error) {
+	eventMap := map[string]struct{}{}
+	var getEvents func(eventIDs []string) ([]*gomatrixserverlib.Event, error)
+	getEvents = func(eventIDs []string) ([]*gomatrixserverlib.Event, error) {
```
Comment (kegsay) [inline roomserver/state/state.go:980]: Please can we do this iteratively (i.e for loop with a queue, see https://github.com/matrix-org/complement/blob/2fdc71eae72c243615df3136008fc00bce4bf3cd/internal/federation/server_room.go#L101 )

**Review by kegsay — COMMENTED** [review]
Not sure if this works the way you want it to without any tests. Probably ok?
