### PR TITLE
Fix `create-account` with global database settings

### LINKED ISSUE #2449: cmd/create-account can't connect global.database
### Background information

- **Dendrite version or git SHA**: 0.8.4
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: Yes
- **`go version`**: -
- **Client used (if applicable)**: Elemnt Web

### Description

 - **What** is the problem:

Since `create-account` command only checks `UserAPI.AccountDatabase`, `global.database` that included in v0.8.3 for monolith can't be connected.

 - **Who** is affected:
Who uses `create-account` command

 - **How** is this bug manifesting:
```
FATA[0004] Failed to connect to the database error="dial tcp 127.0.0.1:5432: connect: connection refused"
```

### Steps to reproduce

- run `create-account` command

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

### PR DESCRIPTION
**Pull request by S7evinK**
Fixes #2449

### CODE REVIEW

File: setup/base/base.go [hunk 1]
```diff
@@ -100,6 +100,7 @@ const (
 	DisableMetrics BaseDendriteOptions = iota
 	UseHTTPAPIs
 	PolylithMode
+	CreateAccountMode
```
Comment (neilalexander) [inline setup/base/base.go:103]: Rather than changing the shape of `base`, can we instead just overwrite the registration disabled flag in the loaded `cfg` in `cmd/create-account/main.go` to `true` before handing it to `NewBaseDendrite`?

**Review by neilalexander — CHANGES_REQUESTED** [review]

**Review by neilalexander — APPROVED** [review]
