### PR TITLE
Randomly generated media IDs

### LINKED ISSUE #1213: Race when uploading files
```
time="2020-07-22T09:00:00.502881100Z" level=warning msg="Failed to store metadata" func="storeFileAndMetadata\n\t" file=" [/build/dendrite-master/mediaapi/routing/upload.go:238]" MediaID=ZjRPeFpYX3hfRk81TGNHQlNLSFdYZnd0U3gtajFuY29TdDNTQUJKdGtHaw Origin=hs1 error="UNIQUE constraint failed: mediaapi_media_repository.media_id, mediaapi_media_repository.media_origin" req.id=oObZ2aQ5uAv7 req.method=POST req.path=/_matrix/media/r0/upload user_id="@alice:hs1"
time="2020-07-22T09:00:00.503122300Z" level=info msg="Responding (50 bytes)" func="respond\n\t" file=" [/go/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:170]" code=400 req.id=oObZ2aQ5uAv7 req.method=POST req.path=/_matrix/media/r0/upload
```
To repro: run complement test `TestMediaWithoutFileName` which does some media uploads/downloads in parallel.

### PR DESCRIPTION
**Pull request by neilalexander**
This generates media IDs from file uploads randomly, therefore each copy of the same upload maintains its own metadata such as content type, uploaded filename etc. However, the file is still stored (and deduplicated) on the filesystem using the hash of the file contents.

This will probably fix #1213.

### CODE REVIEW

**Comment by neilalexander** [comment]
```
=== RUN   TestMediaWithoutFileName
=== RUN   TestMediaWithoutFileName/parallel
=== RUN   TestMediaWithoutFileName/parallel/Can_upload_without_a_file_name
=== PAUSE TestMediaWithoutFileName/parallel/Can_upload_without_a_file_name
=== RUN   TestMediaWithoutFileName/parallel/Can_download_without_a_file_name_locally
=== PAUSE TestMediaWithoutFileName/parallel/Can_download_without_a_file_name_locally
=== RUN   TestMediaWithoutFileName/parallel/Can_download_without_a_file_name_over_federation
=== PAUSE TestMediaWithoutFileName/parallel/Can_download_without_a_file_name_over_federation
=== CONT  TestMediaWithoutFileName/parallel/Can_upload_without_a_file_name
=== CONT  TestMediaWithoutFileName/parallel/Can_download_without_a_file_name_over_federation
=== CONT  TestMediaWithoutFileName/parallel/Can_download_without_a_file_name_locally
    TestMediaWithoutFileName/parallel/Can_download_without_a_file_name_locally: client.go:262: POST /_matrix/media/r0/upload => 200 OK (12.630943ms)
    TestMediaWithoutFileName/parallel/Can_download_without_a_file_name_locally: client.go:262: GET /_matrix/media/r0/download/hs1/e3c2e14830891cd6ae147aa04405cc30f759a31d93684230a2b985c8066ef5d7 => 200 OK (1.430616ms)
    TestMediaWithoutFileName/parallel/Can_upload_without_a_file_name: client.go:262: POST /_matrix/media/r0/upload => 200 OK (19.766519ms)
    TestMediaWithoutFileName/parallel/Can_download_without_a_file_name_over_federation: client.go:262: GET /_matrix/media/r0/download/host.docker.internal/PlainTextFile => 200 OK (30.251094ms)
--- PASS: TestMediaWithoutFileName (2.72s)
    --- PASS: TestMediaWithoutFileName/parallel (0.00s)
        --- PASS: TestMediaWithoutFileName/parallel/Can_upload_without_a_file_name (0.02s)
        --- PASS: TestMediaWithoutFileName/parallel/Can_download_without_a_file_name_locally (0.06s)
        --- PASS: TestMediaWithoutFileName/parallel/Can_download_without_a_file_name_over_federation (0.24s)
```

File: mediaapi/routing/upload.go [hunk 1]
```diff
@@ -93,6 +94,25 @@ func parseAndValidateRequest(req *http.Request, cfg *config.MediaAPI) (*uploadRe
...
+		if err != nil {
+			return "", fmt.Errorf("rand.Read: %w", err)
+		}
+		mediaID := types.MediaID(hex.EncodeToString(mediaIDBytes))
+		existingMetadata, err := db.GetMediaMetadata(ctx, mediaID, r.MediaMetadata.Origin)
+		if err != nil {
+			return "", fmt.Errorf("db.GetMediaMetadata: %w", err)
+		}
+		if existingMetadata != nil {
+			continue
```
Comment (Kegsay) [inline mediaapi/routing/upload.go:110]: Needs commentary.

**Review by Kegsay — APPROVED** [review]
LGTM!
