### PR TITLE
Fix issue with DMs shown as normal rooms

### LINKED ISSUE #2121: DM rooms are displayed as normal rooms
> New 1:1 chat initiate by my synapse server to dentrite shows up under rooms not under person on the dendrite element clienrt

> I see the same. Invite from dendrite homeserver to matrix.org sows up as person, but from matrix.org to homeserver shows up in rooms on the homeserver, both element clients

Could be a few things:
 - Account data isn't sent to clients
 - `is_direct` hints aren't making it across federation
 
Ref: https://spec.matrix.org/v1.1/client-server-api/#direct-messaging

### PR DESCRIPTION
**Pull request by S7evinK**
Fixes #2121, test added in https://github.com/matrix-org/complement/pull/494

### CODE REVIEW

File: federationapi/internal/perform.go [hunk 1]
```diff
@@ -267,6 +270,12 @@ func (r *FederationInternalAPI) performJoinUsingServer(
 	// If we successfully performed a send_join above then the other
 	// server now thinks we're a part of the room. Send the newly
 	// returned state to the roomserver to update our local view.
+	event, err = event.SetUnsigned(unsigned)
+	if err != nil {
+		// non-fatal, log and continue
+		logrus.WithError(err).Errorf("Failed to set prev content")
```
Comment (neilalexander) [inline federationapi/internal/perform.go:276]: Unsigned content?

**Review by neilalexander — APPROVED** [review]
