### PR TITLE
Fix pg user already exists

### LINKED ISSUE #1002: Trying to register an account that already exists returns useless error
`failed to create account: pq: Could not complete operation in a failed transaction`

### PR DESCRIPTION
**Pull request by S7evinK**
Fixes #1002 

### Pull Request Checklist

* [ ] I have added any new tests that need to pass to `testfile` as specified in [docs/sytest.md](https://github.com/matrix-org/dendrite/blob/master/docs/sytest.md)
* [x] Pull request includes a [sign off](https://github.com/matrix-org/dendrite/blob/master/CONTRIBUTING.md#sign-off)

### CODE REVIEW

File: clientapi/auth/storage/accounts/postgres/storage.go [hunk 1]
```diff
@@ -164,7 +164,7 @@ func (d *Database) createAccount(
 	}
 	if err := d.profiles.insertProfile(ctx, txn, localpart); err != nil {
 		if internal.IsUniqueConstraintViolationErr(err) {
-			return nil, nil
+			return nil, internal.ErrUserExists
```
Comment (Kegsay) [inline clientapi/auth/storage/accounts/postgres/storage.go:167]: You need to update `sqlite` as well please to return this sentinel error.

**Comment by S7evinK** [comment]
I've add a `sqlite3.ErrConstraint` check in `internal.IsUniqueConstraintViolationErr`, even though the file is name `postgres.go`.

Also, maybe i should move the new error to the interface file?

File: internal/postgres.go [hunk 2]
```diff
@@ -16,10 +16,22 @@
...
-import "github.com/lib/pq"
+import (
+	"errors"
 
-// IsUniqueConstraintViolationErr returns true if the error is a postgresql unique_violation error
+	"github.com/lib/pq"
+	"github.com/mattn/go-sqlite3"
+)
+
+// IsUniqueConstraintViolationErr returns true if the error is a postgresql unique_violation or sqlite3.ErrConstraint
```
Comment (Kegsay) [inline internal/postgres.go:26]: We can't mix sqlite and postgres in the same file otherwise dendritejs will fail to compile (pq cannot be compiled to WASM). Keep the check contained to `sqlite` packages for now please.

**Comment by Kegsay** [comment]
Please add the function comments to `clientapi/auth/storage/accounts/interface.go` instead of the concrete impls. Thanks!

File: internal/postgres.go (hunk 2 above)
Comment (S7evinK) [reply internal/postgres.go]: I thought since there's also a `postgres_wasm.go` (with `+build wasm`) that this file would be used when compiling for wasm.
Nevertheless, i've reverted the change and moved the check directly to the `sqlite` package.

**Comment by Kegsay** [comment]
LGTM thanks!
