### PR TITLE
Don't ignore config flag for yggdrasil demo if set

### LINKED ISSUE #1756: dendrite-demo-yggdrasil -config 'config_is_ignored.yaml'
### Background information

- **Dendrite version or git SHA**: 0.3.9
- **Monolith or Polylith?**: dendrite-demo-yggdrasil
- **SQLite3 or Postgres?**: sqlite (I would like to switch to postgres but I don't know how to do it)
- **Running in Docker?**: no, compiled with `./build.sh`
- **`go version`**: go version go1.13.6 linux/amd64

### Description

I am testing dendrite yggdrasil in a very old beaglebone, looks like works fine, I crosscompiled it (because it cannot compile by itself, only 256 MB of RAM) with `build.sh` last line with this:

```
CGO_ENABLED=1 CC=arm-linux-gnueabihf-gcc-8 GOOS=linux GOARCH=arm GOARM=6 go build -trimpath -ldflags "$FLAGS" -v -o "${BINDIR}/" ./cmd/...
```

What I want to do is try the yggdrasil demo with postgresql instead of sqlite, because then I expect to get less errors such as:

```
ERRO[2021-02-07T12:51:41.771973870Z] [github.com/matrix-org/dendrite@/syncapi/streams/stream_receipt.go:47] IncrementalSync
         p.DB.RoomReceiptsAfter failed                 device_id=81h8SahK error="database is locked" limit=20 req.id=NA3WqEY5cBJS req.method=GET req.path=/_matrix/client/r0/sync since=s11_8_2_2_3_4.dl-0-2 timeout=30s user_id="@beaglebone:11d3bd92ba64eeafd4f6d216e9d1ecbd333e51d32ddda246cf4e871115aed0c7"
```

Looks like dendrite-demo-yggdrasil is not reading any config file, but output of `dendrite-demo-yggdrasil --help` is confusing (like the config file is going to be read):

```
Usage of bin/dendrite-demo-yggdrasil:
  -config string
    	The path to the config file. For more information, see the config file in this repository. (default "dendrite.yaml")
  -name string
    	the name of this P2P demo instance (default "dendrite-p2p-ygg")
  -peer string
    	an internet Yggdrasil peer to connect to
  -port int
    	the port that the client API will listen on (default 8008)
  -version
    	Shows the current version and exits immediately.
```

I also tried to change `dendrite.yaml` with things such as

```
    connection_string: file:blaaaa__appservice.db
```

to test if really is reading the config file, I suspect that no

### Steps to reproduce

```
[20:17:36] $ bin/dendrite-demo-yggdrasil -config blaaaaaaaaaaaaaaaaaa
YGG 2021/02/07 20:17:39 Starting up...
YGG 2021/02/07 20:17:39 Starting switch
YGG 2021/02/07 20:17:39 Starting router
YGG 2021/02/07 20:17:39 Startup complete
YGG 2021/02/07 20:17:39 Public curve25519: e57556ddae1d439638b7ff7c307080a8aea2cea027620167c84e01fea5162268
YGG 2021/02/07 20:17:39 Public ed25519: [77 252 103 221 157 170 72 235 12 169 245 157 83 234 228 44 208 86 139 210 249 227 78 179 38 34 135 238 70 198 184 64]
YGG 2021/02/07 20:17:39 Reloading multicast configuration...
YGG 2021/02/07 20:17:39 Starting multicast module
INFO[2021-02-07T19:17:39.980269680Z] [github.com/matrix-org/dendrite@/setup/base.go:110] NewBaseDendrite
	 Dendrite version 0.3.9+9a199ba1              
YGG 2021/02/07 20:17:39 Listening for TCP on: [fe80::c37d:46e0:4c4c:f8b7%wlp2s0]:41797
INFO[2021-02-07T19:17:40.000284209Z] [github.com/matrix-org/dendrite@/setup/mscs/mscs.go:31] Enable
	 Enabling MSC                                  context=missing msc=msc2836
INFO[2021-02-07T19:17:40.001249587Z] [github.com/matrix-org/dendrite@/cmd/dendrite-demo-yggdrasil/main.go:196] func5
	 Sending wake-up message to known nodes       
INFO[2021-02-07T19:17:40.001291606Z] [github.com/matrix-org/dendrite@/cmd/dendrite-demo-yggdrasil/main.go:187] func3
	 Listening on 4dfc67dd9daa48eb0ca9f59d53eae42cd0568bd2f9e34eb3262287ee46c6b840 
INFO[2021-02-07T19:17:40.001324422Z] [github.com/matrix-org/dendrite@/cmd/dendrite-demo-yggdrasil/main.go:192] func4
	 Listening on :8008                           
YGG 2021/02/07 20:17:40 Waiting to accept QUIC sessions
```

I would expect an output such as in the case of monolith server:

```
[20:17:51] $ bin/dendrite-monolith-server -config blaaaaaaaaaaaaaaaaaa
FATA[0000] Invalid config file: open blaaaaaaaaaaaaaaaaaa: no such file or directory 
```

### PR DESCRIPTION
**Pull request by bn4t**
Should close  #1756.

Let me know if anything needs to be changed.

### Pull Request Checklist

* [ ] I have added any new tests that need to pass to `sytest-whitelist` as specified in [docs/sytest.md](https://github.com/matrix-org/dendrite/blob/master/docs/sytest.md)
* [X] Pull request includes a [sign off](https://github.com/matrix-org/dendrite/blob/master/docs/CONTRIBUTING.md#sign-off)

Signed-off-by: `bn4t <me@bn4t.me>`

### CODE REVIEW

File: cmd/dendrite-demo-yggdrasil/main.go [hunk 1]
```diff
@@ -72,25 +73,40 @@ func main() {
...
-	cfg.MSCs.Database.ConnectionString = config.DataSource(fmt.Sprintf("file:%s-mscs.db", *instanceName))
-	if err = cfg.Derive(); err != nil {
-		panic(err)
+
+	// use custom config if config flag is set
+	if configFlagSet {
+		cfg = setup.ParseFlags(true)
+	} else {
+		cfg.Defaults(true)
+		cfg.Global.ServerName = gomatrixserverlib.ServerName(ygg.DerivedServerName())
```
Comment (neilalexander) [inline cmd/dendrite-demo-yggdrasil/main.go:92]: I think at a minimum we probably need to make sure that `ServerName`, `PrivateKey` and `KeyID` are *always* overridden, in case the values in the configuration file differ from what they should. Otherwise it's quite likely that the node won't be discoverable/federate properly.

Comment (bn4t) [reply cmd/dendrite-demo-yggdrasil/main.go]: Okay, I now made it so they're always overridden.

**Review by neilalexander — APPROVED** [review]
